spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1800000
      data-source-properties:
        prepareThreshold: 1
        preparedStatementCacheQueries: 256
        preparedStatementCacheSizeMiB: 5

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: ${LIQUIBASE_ENABLED}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}

#  data:
#    mongodb:
#      uri: ${MONGO_URI}
#      database: ${MONGO_DB}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


# Hibernate
hibernate:
  show_sql: ${HIBERNATE_SHOW_SQL:false}
  hbm2ddl:
    auto: validate
  entity:
    package: com.softserve.entity

# Application
app:
  jwt:
    token:
      secret: ${JWT_SECRET}
      expired: ${JWT_EXPIRED:24h}
  backend:
    url: ${BACKEND_URL}
  cors:
    allowed-origins: ${CORS_ORIGINS}

# Redis
redis:
  address: ${REDIS_URL}

# Server
server:
  port: ${PORT:8080}

# Logging
#logging:
#  level:
#    com.softserve: WARN
#    org.hibernate.SQL: ${SQL_LOG_LEVEL:WARN}
#    org.springframework.security: WARN

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    com.softserve: DEBUG